// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseAPKFile() {
  return window['go']['main']['App']['BrowseAPKFile']();
}

export function CheckADBAvailability() {
  return window['go']['main']['App']['CheckADBAvailability']();
}

export function CheckPortInUse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckPortInUse'](arg1, arg2, arg3, arg4);
}

export function CheckSSHConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckSSHConnection'](arg1, arg2, arg3);
}

export function ConfigureHikvisionISAPI(arg1) {
  return window['go']['main']['App']['ConfigureHikvisionISAPI'](arg1);
}

export function DeleteInstallationProfile(arg1) {
  return window['go']['main']['App']['DeleteInstallationProfile'](arg1);
}

export function DeleteSitePreset(arg1) {
  return window['go']['main']['App']['DeleteSitePreset'](arg1);
}

export function DeployExitKioskAPK(arg1) {
  return window['go']['main']['App']['DeployExitKioskAPK'](arg1);
}

export function DeployKioskAPK(arg1) {
  return window['go']['main']['App']['DeployKioskAPK'](arg1);
}

export function DeployToServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeployToServer'](arg1, arg2, arg3, arg4, arg5);
}

export function DiagnoseADBDevice(arg1, arg2) {
  return window['go']['main']['App']['DiagnoseADBDevice'](arg1, arg2);
}

export function GetSitePresets() {
  return window['go']['main']['App']['GetSitePresets']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDeploymentHistory() {
  return window['go']['main']['App']['ListDeploymentHistory']();
}

export function ListInstallationProfiles() {
  return window['go']['main']['App']['ListInstallationProfiles']();
}

export function ReadEntranceKioskConfig(arg1) {
  return window['go']['main']['App']['ReadEntranceKioskConfig'](arg1);
}

export function ReadExitKioskConfig(arg1) {
  return window['go']['main']['App']['ReadExitKioskConfig'](arg1);
}

export function ReadRemoteEnv(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadRemoteEnv'](arg1, arg2, arg3, arg4);
}

export function RedeployProxy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedeployProxy'](arg1, arg2, arg3, arg4);
}

export function RestoreLatestProxyEnvBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreLatestProxyEnvBackup'](arg1, arg2, arg3, arg4);
}

export function RunProxyHealthCheck(arg1, arg2) {
  return window['go']['main']['App']['RunProxyHealthCheck'](arg1, arg2);
}

export function RunServerPreflight(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunServerPreflight'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveEnvConfig(arg1) {
  return window['go']['main']['App']['SaveEnvConfig'](arg1);
}

export function SaveInstallationProfile(arg1) {
  return window['go']['main']['App']['SaveInstallationProfile'](arg1);
}

export function SaveRemoteEnv(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveRemoteEnv'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveSitePreset(arg1) {
  return window['go']['main']['App']['SaveSitePreset'](arg1);
}

export function SendMockCameraEvent(arg1, arg2) {
  return window['go']['main']['App']['SendMockCameraEvent'](arg1, arg2);
}

export function StartProxyLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartProxyLogs'](arg1, arg2, arg3, arg4);
}

export function StopProxyLogs() {
  return window['go']['main']['App']['StopProxyLogs']();
}

export function UpdateEntranceKioskConfig(arg1) {
  return window['go']['main']['App']['UpdateEntranceKioskConfig'](arg1);
}

export function UpdateExitKioskConfig(arg1) {
  return window['go']['main']['App']['UpdateExitKioskConfig'](arg1);
}

export function ValidateEntranceKioskConfig(arg1) {
  return window['go']['main']['App']['ValidateEntranceKioskConfig'](arg1);
}

export function ValidateExitKioskConfig(arg1) {
  return window['go']['main']['App']['ValidateExitKioskConfig'](arg1);
}

export function ValidateHikvisionConfig(arg1) {
  return window['go']['main']['App']['ValidateHikvisionConfig'](arg1);
}

export function ValidateProxyEnv(arg1) {
  return window['go']['main']['App']['ValidateProxyEnv'](arg1);
}
