// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseAPKFile():Promise<string>;

export function CheckPortInUse(arg1:string,arg2:string,arg3:string,arg4:number):Promise<boolean>;

export function CheckSSHConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ConfigureHikvisionISAPI(arg1:main.HikvisionConfig):Promise<void>;

export function DeployExitKioskAPK(arg1:main.ExitKioskDeployConfig):Promise<void>;

export function DeployKioskAPK(arg1:main.KioskDeployConfig):Promise<void>;

export function DeployToServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadRemoteEnv(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RedeployProxy(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveEnvConfig(arg1:string):Promise<string>;

export function SaveRemoteEnv(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
