// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseAPKFile() {
  return window['go']['main']['App']['BrowseAPKFile']();
}

export function CheckPortInUse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckPortInUse'](arg1, arg2, arg3, arg4);
}

export function CheckSSHConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckSSHConnection'](arg1, arg2, arg3);
}

export function ConfigureHikvisionISAPI(arg1) {
  return window['go']['main']['App']['ConfigureHikvisionISAPI'](arg1);
}

export function DeployExitKioskAPK(arg1) {
  return window['go']['main']['App']['DeployExitKioskAPK'](arg1);
}

export function DeployKioskAPK(arg1) {
  return window['go']['main']['App']['DeployKioskAPK'](arg1);
}

export function DeployToServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeployToServer'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadEntranceKioskConfig(arg1) {
  return window['go']['main']['App']['ReadEntranceKioskConfig'](arg1);
}

export function ReadExitKioskConfig(arg1) {
  return window['go']['main']['App']['ReadExitKioskConfig'](arg1);
}

export function ReadRemoteEnv(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadRemoteEnv'](arg1, arg2, arg3, arg4);
}

export function RedeployProxy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedeployProxy'](arg1, arg2, arg3, arg4);
}

export function SaveEnvConfig(arg1) {
  return window['go']['main']['App']['SaveEnvConfig'](arg1);
}

export function SaveRemoteEnv(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveRemoteEnv'](arg1, arg2, arg3, arg4, arg5);
}

export function SendMockCameraEvent(arg1, arg2) {
  return window['go']['main']['App']['SendMockCameraEvent'](arg1, arg2);
}

export function UpdateEntranceKioskConfig(arg1) {
  return window['go']['main']['App']['UpdateEntranceKioskConfig'](arg1);
}

export function UpdateExitKioskConfig(arg1) {
  return window['go']['main']['App']['UpdateExitKioskConfig'](arg1);
}
